apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dashboard
  namespace: default
spec:
  encryptedData:
    DASH_PASW: AgBQw0Tc6JAhsZ7er9zXWHBETDLJ8CypvxdU3rzxsWzIp7Uv3ti6g6xPRa+Rdabzly73MmMegvXcrYdfs8I7dIGTsmnEUtVZqvHzHkl+qdTyej4s3UbnrOUD+xsAkCbDZgubbS8QqybKLEB3jwFlP9KH6URwWTZ5OUhv/+0/9qG7JiK2XdfK8w3D2lDNrOZEJ3Ar2lS6qprEizQYT35iiZGDKfQQ+eFYw/XbfEekrcOqFu11m58T9x2UYCNrpQBN19Cl7/YBmcjoY8WO+2Q3xj5y2Tqxj8NT55F79hmfY1BwUqr+8Pu8z2lI+bwS1m3W+mGqnjK2pAgBbvGOF+UdO6w/oNrDPdDRm0xr6/b1JslRee1RpmchBCev3Qr0NvdGbCuyqDmy61+JL+9fcHLHu3aJwz3rPweM9oxJrQU1eBKj2FnmNlJvTumv702EQKzaj1vYrT797Zb/009eaA49DXpS9cqhjyUvArXO6WaEX5OygoQpGW1vz9kL+c3GYsbMNq2eufc1fWDSpKcGNDs8QJ+y0bEKFAzqlaJldA4D7mukpIOuXXEgwOiDJsPn3gF/7g/dKyH0tqsrvUqyDHbKSr8GXmAHXg+Q7F1hFk43gA/k1Lax/GIYaiKU15E+cjyE9hHyrBlXNzYRVjJFqmN76JuCCMSwrIUNIbio0QUr3Y0+FCrIGeIaPBhI9bu7WuUqNWZbOAFynyDxSrG1C8NLkQ==
  template:
    metadata:
      creationTimestamp: null
      name: dashboard
      namespace: default
---
